name: PAY CLAUSULA PLAYER 1
on:
  workflow_dispatch:
  schedule:
    - cron: '50 21 * * 2' # Runs every Sunday at 23:50h // 2h difference with server.

jobs:
  invoke-template:
    uses: ./.github/workflows/pay-clausulazo-template.yml
    with:
      player_id: ${{ vars.PLAYER_ID1 }}
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
      CHAMPIONSHIP_ID: ${{ secrets.CHAMPIONSHIP_ID }}
      USER_TEAM_ID: ${{ secrets.USER_TEAM_ID }}
      USER_ID: ${{ secrets.USER_ID }}
      
