name: Pay Clausulazo

on:
  workflow_dispatch:
    inputs:
      player_id:
        description: 'Player ID'
        required: true
      player_slug:
        description: 'Player Slug'
        required: true
      price:
        description: 'Price'
        required: true
env:
  TOKEN: ${{ secrets.TOKEN }}
  PLAYER_ID: ${{ inputs.player_id }}
  PLAYER_SLUG: ${{ inputs.player_slug }}
  PRICE: ${{ inputs.price }}

jobs:
  pay-clausulazo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node get-player-data.js
