name: PAY CLAUSULA PLAYER 3
on:
  workflow_dispatch:
  schedule:
    - cron: '50 21 * * 2' # Runs every Sunday at 23:50h // 2h difference with server.

jobs:
  invoke-template:
    uses: ./.github/workflows/pay-clausulazo-template.yml
    with:
      player_id: ${{ vars.PLAYER_ID3 }}
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
